### PR TITLE
Witnet Research header design

### PR DESCRIPTION
**Pull request by GuistF**
header
Here is my submission for this GITCOIN issue.
I attached the zip file with .svg, along with file in .psd and png. With some suggestions of the logo.
I waiting for your feedback

[Witnet Logo.zip](https://github.com/witnet/research/files/3110041/Witnet.Logo.zip)

### CODE REVIEW

**Comment by GuistF** [comment]
Here's another design.
header_design
[header2.zip](https://github.com/witnet/research/files/3113019/header2.zip)

**Comment by GuistF** [comment]
Here is another design for Witnet Research.

header3
[header.zip](https://github.com/witnet/research/files/3169524/header.zip)

**Comment by GuistF** [comment]
I developed new designs for Witnet-Rust and Sheikah.

header1

header2

**Comment by aesedepece** [comment]
Hey @GuistF those look super good... sounds like a winner!

I personally like the one for Sheikah the most. The other two look too similar to each other IMO.

As for the general aspect, the shape in the bottom left side looks to pointy to me. I'd try to make it not so high, i.e. moving the corner node up. 

Btw, the font used in witnet-rust is [Quantify](https://www.dafont.com/quantify.font).

**Comment by GuistF** [comment]
I'm glad you liked it, I will make some changes on Sheikah and research color header.
Thanks for indicates the font, now make sense for me :)

Do you want  Quantify/Titillium fonts in all headers?

**Comment by aesedepece** [comment]
The colors for Sheikah are just fine.

The Quantify + Titillium pairing seems to work for all of them, but feel free to use different fonts for each.

**Comment by GuistF** [comment]
Ok, thanks for the feedback, I'll make some changes and return for your evaluation.

**Comment by GuistF** [comment]
Here are the changes to Sheikah and Research. Following editable file in .svg  and .ai . 
header1
header
[Witnet_headers.zip](https://github.com/witnet/research/files/3173321/Witnet_headers.zip)

I leave my availability to make any additional changes.

If it is necessary here my contact: guistfrog@gmail.com
https://twitter.com/g_uist

**Comment by GuistF** [comment]
I'm waiting for your feedback for this new headers update.

**Comment by aesedepece** [comment]
Still the bottom left corner looks too pointy. Let's try moving the corner node up.

**Comment by GuistF** [comment]
Do you want it to look like the old design without waves?
Please check below other options on zip file
[hp.zip](https://github.com/witnet/research/files/3174094/hp.zip)

**Comment by GuistF** [comment]
Please,  keep me updated with your decision,  so that after i can export the right design in svg and png.

**Pull request closed without merging**
